ROLES_DISPONIBLES = (
    "COMERCIAL",
    "DIGITAL",
    "REALIZACIONES",
    "ADMIN",
    "NOTICIERO",
    "RRHH",
    "TECNICA",
    "IT",
)

PERFILES_DISPONIBLES = ("USUARIO", "JEFE")

CONVENIOS_DISPONIBLES = ("CISPREN", "SAL", "SAT", "FC")
